<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Game;
use App\Models\GameScreenshot;
use App\Models\GameSystemRequirement;
use Illuminate\Database\Seeder;

class GameSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $categoriesMap = Category::pluck('id', 'slug')->toArray();

        $games = [
            [
                'title' => 'Shattered Pixel Dungeon',
                'slug' => 'shattered-pixel-dungeon',
                'short_description' => 'Classic open-source roguelike RPG dungeon crawler with 5 unique hero classes.',
                'description' => 'Shattered Pixel Dungeon is a traditional roguelike RPG game that is simple to get into but hard to master! Every game is a unique challenge, with five different heroes, randomized levels and enemies, and hundreds of items to collect and use.',
                'developer' => '00-Evan',
                'publisher' => 'Shattered Pixel Labs',
                'game_type' => 'open-source',
                'release_date' => '2022-03-15',
                'version' => 'v2.4.2',
                'file_size' => '85 MB',
                'cover_image' => 'https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=600&q=80',
                'banner_image' => 'https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&w=1600&q=80',
                'supported_languages' => ['English', 'Indonesian', 'Japanese', 'German', 'Spanish'],
                'last_updated' => '2025-01-20',
                'rating' => 4.8,
                'download_count' => 1200000,
                'official_source_name' => 'GitHub Repository',
                'official_source_url' => 'https://github.com/00-Evan/shattered-pixel-dungeon',
                'status' => 'published',
                'featured' => true,
                'category_slugs' => ['rpg', 'indie', 'strategy'],
                'min_req' => ['os' => 'Windows 7 / 8 / 10 / 11', 'processor' => 'Dual Core 1.8 GHz', 'memory' => '1 GB RAM', 'graphics' => 'OpenGL 2.0 compatible', 'storage' => '200 MB', 'directx' => 'Version 9.0c'],
                'rec_req' => ['os' => 'Windows 10 / 11 (64-bit)', 'processor' => 'Quad Core 2.4 GHz', 'memory' => '2 GB RAM', 'graphics' => 'OpenGL 3.0+ dedicated GPU', 'storage' => '500 MB', 'directx' => 'Version 11'],
                'screenshots' => [
                    'https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=1200&q=80',
                    'https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&w=1200&q=80',
                ],
            ],
            [
                'title' => 'Trackmania Nations Forever',
                'slug' => 'trackmania-nations-forever',
                'short_description' => 'Legendary free arcade racing game with stunt physics and online multiplayer.',
                'description' => 'TrackMania Nations Forever lets you drive at mind-blowing speeds on fun and spectacular tracks in solo and multiplayer modes. Features 65 brand new, challenging tracks, and complete community track editor.',
                'developer' => 'Nadeo',
                'publisher' => 'Ubisoft',
                'game_type' => 'free-to-play',
                'release_date' => '2008-04-16',
                'version' => 'v2.11.26',
                'file_size' => '504 MB',
                'cover_image' => 'https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&w=600&q=80',
                'banner_image' => 'https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=1600&q=80',
                'supported_languages' => ['English', 'French', 'German', 'Italian'],
                'last_updated' => '2024-08-10',
                'rating' => 4.9,
                'download_count' => 3400000,
                'official_source_name' => 'Steam Official Free',
                'official_source_url' => 'https://store.steampowered.com/app/11020/TrackMania_Nations_Forever/',
                'status' => 'published',
                'featured' => true,
                'category_slugs' => ['racing', 'sports', 'multiplayer'],
                'min_req' => ['os' => 'Windows 2000 / XP / Vista / 7 / 10', 'processor' => 'Pentium IV 1.6 GHz', 'memory' => '512 MB RAM', 'graphics' => '3D 16 MB DirectX 9.0c', 'storage' => '1.5 GB', 'directx' => 'Version 9.0c'],
                'rec_req' => ['os' => 'Windows 10 / 11 (64-bit)', 'processor' => 'Core 2 Duo 2.0 GHz', 'memory' => '2 GB RAM', 'graphics' => 'Dedicated GPU 256 MB', 'storage' => '2 GB', 'directx' => 'Version 9.0c'],
                'screenshots' => [
                    'https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&w=1200&q=80',
                    'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=1200&q=80',
                ],
            ],
            [
                'title' => 'Beyond All Reason',
                'slug' => 'beyond-all-reason',
                'short_description' => 'Spectacular next-generation open-source RTS with massive battles.',
                'description' => 'Beyond All Reason (BAR) is a modern, open-source Real-Time Strategy game inspired by Total Annihilation and Spring engine. Command thousands of units across immense war fronts in fluid 60fps warfare.',
                'developer' => 'BAR Team',
                'publisher' => 'Open Source Community',
                'game_type' => 'open-source',
                'release_date' => '2023-01-10',
                'version' => 'v1.4.0',
                'file_size' => '2.1 GB',
                'cover_image' => 'https://images.unsplash.com/photo-1579373903781-fd5c0c30c4cd?auto=format&fit=crop&w=600&q=80',
                'banner_image' => 'https://images.unsplash.com/photo-1538481199705-c710c4e965fc?auto=format&fit=crop&w=1600&q=80',
                'supported_languages' => ['English', 'German', 'Russian', 'French'],
                'last_updated' => '2025-02-01',
                'rating' => 4.9,
                'download_count' => 890000,
                'official_source_name' => 'Official BAR Website',
                'official_source_url' => 'https://www.beyondallreason.info/',
                'status' => 'published',
                'featured' => true,
                'category_slugs' => ['strategy', 'multiplayer', 'action'],
                'min_req' => ['os' => 'Windows 10 (64-bit)', 'processor' => 'Intel Core i3 / AMD Ryzen 3', 'memory' => '4 GB RAM', 'graphics' => 'NVIDIA GT 1030 / AMD RX 550', 'storage' => '4 GB', 'directx' => 'Version 11'],
                'rec_req' => ['os' => 'Windows 11 (64-bit)', 'processor' => 'Intel Core i5 / AMD Ryzen 5', 'memory' => '8 GB RAM', 'graphics' => 'NVIDIA GTX 1060 6GB / AMD RX 580', 'storage' => '8 GB', 'directx' => 'Version 11'],
                'screenshots' => [
                    'https://images.unsplash.com/photo-1579373903781-fd5c0c30c4cd?auto=format&fit=crop&w=1200&q=80',
                ],
            ],
            [
                'title' => 'OpenRA',
                'slug' => 'open-ra',
                'short_description' => 'Modern recreation of classic 90s Real-Time Strategy games.',
                'description' => 'OpenRA is a Libre/Free Real Time Strategy game engine supporting classic Westwood titles including Command & Conquer and Red Alert in modern resolutions and multiplayer netcode.',
                'developer' => 'OpenRA Community',
                'publisher' => 'OpenRA Project',
                'game_type' => 'open-source',
                'release_date' => '2021-06-20',
                'version' => 'release-20231010',
                'file_size' => '82 MB',
                'cover_image' => 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=600&q=80',
                'banner_image' => 'https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=1600&q=80',
                'supported_languages' => ['English', 'German', 'Polish', 'Russian'],
                'last_updated' => '2024-11-15',
                'rating' => 4.7,
                'download_count' => 650000,
                'official_source_name' => 'OpenRA Official Portal',
                'official_source_url' => 'https://www.openra.net/',
                'status' => 'published',
                'featured' => false,
                'category_slugs' => ['strategy', 'multiplayer'],
                'min_req' => ['os' => 'Windows 7 or later', 'processor' => '1.5 GHz Dual Core', 'memory' => '2 GB RAM', 'graphics' => 'OpenGL 2.1 support', 'storage' => '500 MB', 'directx' => 'Version 9.0c'],
                'rec_req' => ['os' => 'Windows 10 / 11', 'processor' => '2.5 GHz Quad Core', 'memory' => '4 GB RAM', 'graphics' => 'Dedicated GPU 1 GB', 'storage' => '1 GB', 'directx' => 'Version 11'],
                'screenshots' => [
                    'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=1200&q=80',
                ],
            ],
            [
                'title' => 'Veloren',
                'slug' => 'veloren',
                'short_description' => 'Open-world voxel multiplayer RPG created in Rust.',
                'description' => 'Veloren is an open-world, open-source multiplayer voxel RPG inspired by Cube World, Legend of Zelda: Breath of the Wild, Dwarf Fortress, and Minecraft.',
                'developer' => 'Veloren Core Developers',
                'publisher' => 'Veloren Foundation',
                'game_type' => 'open-source',
                'release_date' => '2023-08-01',
                'version' => 'v0.15.0',
                'file_size' => '850 MB',
                'cover_image' => 'https://images.unsplash.com/photo-1538481199705-c710c4e965fc?auto=format&fit=crop&w=600&q=80',
                'banner_image' => 'https://images.unsplash.com/photo-1579373903781-fd5c0c30c4cd?auto=format&fit=crop&w=1600&q=80',
                'supported_languages' => ['English', 'German', 'French', 'Chinese'],
                'last_updated' => '2025-01-10',
                'rating' => 4.8,
                'download_count' => 780000,
                'official_source_name' => 'Veloren Gitlab / Website',
                'official_source_url' => 'https://veloren.net/',
                'status' => 'published',
                'featured' => false,
                'category_slugs' => ['rpg', 'adventure', 'multiplayer'],
                'min_req' => ['os' => 'Windows 10 (64-bit)', 'processor' => 'Quad Core 2.0 GHz', 'memory' => '4 GB RAM', 'graphics' => 'OpenGL 3.2 / Vulkan compatible', 'storage' => '2 GB', 'directx' => 'Version 11'],
                'rec_req' => ['os' => 'Windows 11 (64-bit)', 'processor' => 'Hexa Core 3.2 GHz', 'memory' => '8 GB RAM', 'graphics' => 'NVIDIA GTX 1650 / AMD RX 570', 'storage' => '4 GB', 'directx' => 'Version 12'],
                'screenshots' => [
                    'https://images.unsplash.com/photo-1538481199705-c710c4e965fc?auto=format&fit=crop&w=1200&q=80',
                ],
            ],
            [
                'title' => 'SuperTuxKart',
                'slug' => 'supertuxkart',
                'short_description' => '3D open-source arcade kart racing game with diverse tracks and characters.',
                'description' => 'SuperTuxKart is an open-source 3D arcade kart racer featuring Tux and friends. Discover an immersive story mode, split-screen and online multiplayer, with tons of fun items.',
                'developer' => 'STK Development Team',
                'publisher' => 'SuperTuxKart Project',
                'game_type' => 'open-source',
                'release_date' => '2022-11-01',
                'version' => 'v1.4',
                'file_size' => '720 MB',
                'cover_image' => 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=600&q=80',
                'banner_image' => 'https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&w=1600&q=80',
                'supported_languages' => ['English', 'Indonesian', 'French', 'German', 'Italian'],
                'last_updated' => '2024-09-12',
                'rating' => 4.6,
                'download_count' => 1800000,
                'official_source_name' => 'SuperTuxKart Portal',
                'official_source_url' => 'https://supertuxkart.net/',
                'status' => 'published',
                'featured' => false,
                'category_slugs' => ['racing', 'sports', 'indie'],
                'min_req' => ['os' => 'Windows 7 / 8 / 10', 'processor' => 'Dual Core 1.5 GHz', 'memory' => '1 GB RAM', 'graphics' => 'Intel HD 3000 / ATI Radeon HD 2000', 'storage' => '1.5 GB', 'directx' => 'Version 9.0c'],
                'rec_req' => ['os' => 'Windows 10 / 11 (64-bit)', 'processor' => 'Quad Core 2.5 GHz', 'memory' => '4 GB RAM', 'graphics' => 'NVIDIA GT 740 / AMD RX 460', 'storage' => '2 GB', 'directx' => 'Version 11'],
                'screenshots' => [
                    'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=1200&q=80',
                ],
            ],
            [
                'title' => '0 A.D. Empires Ascendant',
                'slug' => '0-ad',
                'short_description' => 'Free, open-source real-time strategy game of ancient warfare.',
                'description' => '0 A.D. (pronounced zero ey-dee) is a historical RTS game set between 500 B.C. and 500 A.D., featuring civilizations such as the Romans, Carthaginians, Greeks, Persians, and Mauryans.',
                'developer' => 'Wildfire Games',
                'publisher' => 'Wildfire Games',
                'game_type' => 'open-source',
                'release_date' => '2022-09-24',
                'version' => 'Alpha 26',
                'file_size' => '1.8 GB',
                'cover_image' => 'https://images.unsplash.com/photo-1563089145-599997674d42?auto=format&fit=crop&w=600&q=80',
                'banner_image' => 'https://images.unsplash.com/photo-1579373903781-fd5c0c30c4cd?auto=format&fit=crop&w=1600&q=80',
                'supported_languages' => ['English', 'German', 'Spanish', 'French'],
                'last_updated' => '2024-10-18',
                'rating' => 4.7,
                'download_count' => 920000,
                'official_source_name' => 'Wildfire Games Portal',
                'official_source_url' => 'https://play0ad.com/',
                'status' => 'published',
                'featured' => false,
                'category_slugs' => ['strategy', 'simulation'],
                'min_req' => ['os' => 'Windows 7 / 8 / 10', 'processor' => 'Intel Core 2 or AMD Athlon 64', 'memory' => '2 GB RAM', 'graphics' => 'DirectX 9.0c with 128 MB VRAM', 'storage' => '3 GB', 'directx' => 'Version 9.0c'],
                'rec_req' => ['os' => 'Windows 10 / 11 (64-bit)', 'processor' => 'Core i5 3.0 GHz', 'memory' => '4 GB RAM', 'graphics' => 'GeForce GTX 750 / Radeon R7 260', 'storage' => '5 GB', 'directx' => 'Version 11'],
                'screenshots' => [
                    'https://images.unsplash.com/photo-1563089145-599997674d42?auto=format&fit=crop&w=1200&q=80',
                ],
            ],
            [
                'title' => 'Mindustry',
                'slug' => 'mindustry',
                'short_description' => 'Open-source tower defense and factory building automation game.',
                'description' => 'Mindustry is a sandbox tower-defense and logistics management game. Create elaborate supply chains of conveyor belts to feed ammo into your turrets and defend your core against enemy waves.',
                'developer' => 'Anuken',
                'publisher' => 'Anuke Studios',
                'game_type' => 'open-source',
                'release_date' => '2021-12-05',
                'version' => 'v7.0 (Build 146)',
                'file_size' => '75 MB',
                'cover_image' => 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=600&q=80',
                'banner_image' => 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=1600&q=80',
                'supported_languages' => ['English', 'Indonesian', 'Japanese', 'Korean', 'Russian'],
                'last_updated' => '2024-12-14',
                'rating' => 4.9,
                'download_count' => 1650000,
                'official_source_name' => 'GitHub Releases',
                'official_source_url' => 'https://github.com/Anuken/Mindustry',
                'status' => 'published',
                'featured' => true,
                'category_slugs' => ['strategy', 'simulation', 'indie'],
                'min_req' => ['os' => 'Windows 7 / 8 / 10 / 11', 'processor' => 'Any dual core 1.6 GHz', 'memory' => '1 GB RAM', 'graphics' => 'OpenGL 2.0 compatible', 'storage' => '200 MB', 'directx' => 'Version 9.0c'],
                'rec_req' => ['os' => 'Windows 10 / 11', 'processor' => 'Dual Core 2.4 GHz', 'memory' => '2 GB RAM', 'graphics' => 'Dedicated graphics card', 'storage' => '500 MB', 'directx' => 'Version 11'],
                'screenshots' => [
                    'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1200&q=80',
                ],
            ],
            [
                'title' => 'Endless Sky',
                'slug' => 'endless-sky',
                'short_description' => '2D space trading and combat game inspired by Escape Velocity.',
                'description' => 'Endless Sky is a 2D space trading and combat simulation. Earn money by trading, carrying passengers, or completing missions. Explore diverse alien civilizations and upgrade your starship.',
                'developer' => 'Michael Zahniser',
                'publisher' => 'Endless Sky Community',
                'game_type' => 'open-source',
                'release_date' => '2015-10-30',
                'version' => 'v0.10.6',
                'file_size' => '240 MB',
                'cover_image' => 'https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?auto=format&fit=crop&w=600&q=80',
                'banner_image' => 'https://images.unsplash.com/photo-1538481199705-c710c4e965fc?auto=format&fit=crop&w=1600&q=80',
                'supported_languages' => ['English', 'German', 'Spanish'],
                'last_updated' => '2024-07-20',
                'rating' => 4.8,
                'download_count' => 610000,
                'official_source_name' => 'Steam / GitHub Portal',
                'official_source_url' => 'https://endless-sky.github.io/',
                'status' => 'published',
                'featured' => false,
                'category_slugs' => ['adventure', 'simulation', 'rpg'],
                'min_req' => ['os' => 'Windows 7 / 8 / 10', 'processor' => '1.5 GHz', 'memory' => '1 GB RAM', 'graphics' => 'OpenGL 3.0 support', 'storage' => '350 MB', 'directx' => 'Version 9.0c'],
                'rec_req' => ['os' => 'Windows 10 / 11', 'processor' => '2.0 GHz Dual Core', 'memory' => '2 GB RAM', 'graphics' => 'Dedicated graphics card', 'storage' => '1 GB', 'directx' => 'Version 11'],
                'screenshots' => [
                    'https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?auto=format&fit=crop&w=1200&q=80',
                ],
            ],
            [
                'title' => 'The Dark Mod',
                'slug' => 'the-dark-mod',
                'short_description' => 'First-person stealth game inspired by the legendary Thief series.',
                'description' => 'The Dark Mod is a standalone open-source first-person stealth game. You play as an agile thief in a grim steampunk dark-fantasy world, relying on shadows, lockpicking, and wits to survive.',
                'developer' => 'Broken Glass Studios',
                'publisher' => 'The Dark Mod Team',
                'game_type' => 'freeware',
                'release_date' => '2020-02-14',
                'version' => 'v2.12',
                'file_size' => '3.8 GB',
                'cover_image' => 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=600&q=80',
                'banner_image' => 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=1600&q=80',
                'supported_languages' => ['English', 'German', 'Italian', 'French'],
                'last_updated' => '2024-05-18',
                'rating' => 4.7,
                'download_count' => 430000,
                'official_source_name' => 'The Dark Mod Official Web',
                'official_source_url' => 'https://www.thedarkmod.com/',
                'status' => 'published',
                'featured' => false,
                'category_slugs' => ['horror', 'action', 'adventure'],
                'min_req' => ['os' => 'Windows 7 / 8 / 10 (64-bit)', 'processor' => 'Dual Core 2.4 GHz', 'memory' => '4 GB RAM', 'graphics' => 'OpenGL 3.3 compatible (1 GB VRAM)', 'storage' => '5 GB', 'directx' => 'Version 11'],
                'rec_req' => ['os' => 'Windows 10 / 11 (64-bit)', 'processor' => 'Quad Core 3.0 GHz', 'memory' => '8 GB RAM', 'graphics' => 'GeForce GTX 960 / Radeon R9 280', 'storage' => '10 GB', 'directx' => 'Version 11'],
                'screenshots' => [
                    'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=1200&q=80',
                ],
            ],
            [
                'title' => 'Xonotic',
                'slug' => 'xonotic',
                'short_description' => 'Addictive arena-style first person shooter with crisp movement.',
                'description' => 'Xonotic is an addictive, arena-style first person shooter with crisp movement and a wide array of weapons. It combines visceral action with breathtaking multiplayer maps.',
                'developer' => 'Team Xonotic',
                'publisher' => 'Xonotic Community',
                'game_type' => 'open-source',
                'release_date' => '2022-06-25',
                'version' => 'v0.8.6',
                'file_size' => '1.2 GB',
                'cover_image' => 'https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=600&q=80',
                'banner_image' => 'https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&w=1600&q=80',
                'supported_languages' => ['English', 'French', 'Russian'],
                'last_updated' => '2024-04-10',
                'rating' => 4.6,
                'download_count' => 840000,
                'official_source_name' => 'Xonotic Official Portal',
                'official_source_url' => 'https://xonotic.org/',
                'status' => 'published',
                'featured' => false,
                'category_slugs' => ['action', 'multiplayer'],
                'min_req' => ['os' => 'Windows 7 / 8 / 10', 'processor' => 'Dual Core 1.8 GHz', 'memory' => '2 GB RAM', 'graphics' => 'OpenGL 2.0 capable GPU', 'storage' => '2 GB', 'directx' => 'Version 9.0c'],
                'rec_req' => ['os' => 'Windows 10 / 11 (64-bit)', 'processor' => 'Quad Core 2.8 GHz', 'memory' => '4 GB RAM', 'graphics' => 'Dedicated GPU 2 GB VRAM', 'storage' => '4 GB', 'directx' => 'Version 11'],
                'screenshots' => [
                    'https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=1200&q=80',
                ],
            ],
            [
                'title' => 'Warzone 2100',
                'slug' => 'warzone-2100',
                'short_description' => 'Post-apocalyptic 3D real-time strategy game with modular unit design.',
                'description' => 'In Warzone 2100, you command the forces of The Project in a battle to rebuild the world after mankind has almost been destroyed by nuclear missiles.',
                'developer' => 'Pumpkin Studios / Warzone 2100 Project',
                'publisher' => 'Warzone 2100 Community',
                'game_type' => 'open-source',
                'release_date' => '2021-04-10',
                'version' => 'v4.4.2',
                'file_size' => '320 MB',
                'cover_image' => 'https://images.unsplash.com/photo-1579373903781-fd5c0c30c4cd?auto=format&fit=crop&w=600&q=80',
                'banner_image' => 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=1600&q=80',
                'supported_languages' => ['English', 'German', 'Italian', 'Russian'],
                'last_updated' => '2024-11-28',
                'rating' => 4.5,
                'download_count' => 720000,
                'official_source_name' => 'Warzone 2100 Official',
                'official_source_url' => 'https://wz2100.net/',
                'status' => 'published',
                'featured' => false,
                'category_slugs' => ['strategy', 'action', 'multiplayer'],
                'min_req' => ['os' => 'Windows 7 / 8 / 10', 'processor' => '2.0 GHz CPU', 'memory' => '2 GB RAM', 'graphics' => 'OpenGL 3.0 support', 'storage' => '1 GB', 'directx' => 'Version 9.0c'],
                'rec_req' => ['os' => 'Windows 10 / 11 (64-bit)', 'processor' => '3.0 GHz Quad Core', 'memory' => '4 GB RAM', 'graphics' => 'Dedicated GPU 1 GB', 'storage' => '2 GB', 'directx' => 'Version 11'],
                'screenshots' => [
                    'https://images.unsplash.com/photo-1579373903781-fd5c0c30c4cd?auto=format&fit=crop&w=1200&q=80',
                ],
            ],
            [
                'title' => 'Hedgewars',
                'slug' => 'hedgewars',
                'short_description' => 'Hilarious turn-based strategy, artillery, action and comedy game.',
                'description' => 'Hedgewars is a turn-based strategy, artillery, action and comedy game, featuring the antics of pink hedgehogs with attitude as they battle from the depths of hell to the depths of space.',
                'developer' => 'Hedgewars Team',
                'publisher' => 'Open Source Community',
                'game_type' => 'open-source',
                'release_date' => '2021-08-15',
                'version' => 'v1.0.2',
                'file_size' => '210 MB',
                'cover_image' => 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=600&q=80',
                'banner_image' => 'https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=1600&q=80',
                'supported_languages' => ['English', 'German', 'Spanish', 'French'],
                'last_updated' => '2023-12-05',
                'rating' => 4.6,
                'download_count' => 540000,
                'official_source_name' => 'Hedgewars Portal',
                'official_source_url' => 'https://www.hedgewars.org/',
                'status' => 'published',
                'featured' => false,
                'category_slugs' => ['strategy', 'multiplayer', 'indie'],
                'min_req' => ['os' => 'Windows 7 / 8 / 10', 'processor' => '1.0 GHz CPU', 'memory' => '512 MB RAM', 'graphics' => 'OpenGL capable GPU', 'storage' => '500 MB', 'directx' => 'Version 9.0c'],
                'rec_req' => ['os' => 'Windows 10 / 11', 'processor' => '2.0 GHz CPU', 'memory' => '2 GB RAM', 'graphics' => 'Dedicated graphics', 'storage' => '1 GB', 'directx' => 'Version 11'],
                'screenshots' => [
                    'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=1200&q=80',
                ],
            ],
            [
                'title' => 'Cataclysm: Dark Days Ahead',
                'slug' => 'cataclysm-dda',
                'short_description' => 'Turn-based survival game set in a post-apocalyptic procedural world.',
                'description' => 'Cataclysm: Dark Days Ahead is a turn-based survival game set in a post-apocalyptic world. Struggle to survive in a harsh, persistent, procedurally generated world.',
                'developer' => 'CleverRaven',
                'publisher' => 'Open Source Community',
                'game_type' => 'open-source',
                'release_date' => '2023-03-01',
                'version' => '0.G Gaiman',
                'file_size' => '180 MB',
                'cover_image' => 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=600&q=80',
                'banner_image' => 'https://images.unsplash.com/photo-1579373903781-fd5c0c30c4cd?auto=format&fit=crop&w=1600&q=80',
                'supported_languages' => ['English', 'Japanese', 'Russian', 'German'],
                'last_updated' => '2024-09-02',
                'rating' => 4.9,
                'download_count' => 670000,
                'official_source_name' => 'CDDA Official Web',
                'official_source_url' => 'https://cataclysmdda.org/',
                'status' => 'published',
                'featured' => false,
                'category_slugs' => ['rpg', 'horror', 'simulation', 'indie'],
                'min_req' => ['os' => 'Windows 7 / 8 / 10 / 11', 'processor' => 'Any modern 1.5 GHz', 'memory' => '1 GB RAM', 'graphics' => 'DirectX 9 / OpenGL', 'storage' => '500 MB', 'directx' => 'Version 9.0c'],
                'rec_req' => ['os' => 'Windows 10 / 11 (64-bit)', 'processor' => 'Dual Core 2.5 GHz', 'memory' => '4 GB RAM', 'graphics' => 'DirectX 11 Graphics', 'storage' => '1 GB', 'directx' => 'Version 11'],
                'screenshots' => [
                    'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=1200&q=80',
                ],
            ],
            // 2 Draft Games for Admin Testing
            [
                'title' => 'Project Nebula Star (Demo)',
                'slug' => 'project-nebula-star-demo',
                'short_description' => 'Unreleased sci-fi tactical exploration combat simulation demo.',
                'description' => 'Project Nebula Star is an upcoming space exploration simulator featuring deep star system orbital physics, mining, and dynamic tactical fleet battles.',
                'developer' => 'Cosmic Forge Labs',
                'publisher' => 'Indie Publisher',
                'game_type' => 'demo',
                'release_date' => '2026-11-20',
                'version' => 'v0.1.0-alpha',
                'file_size' => '1.5 GB',
                'cover_image' => 'https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?auto=format&fit=crop&w=600&q=80',
                'banner_image' => 'https://images.unsplash.com/photo-1538481199705-c710c4e965fc?auto=format&fit=crop&w=1600&q=80',
                'supported_languages' => ['English', 'Indonesian'],
                'last_updated' => '2026-02-15',
                'rating' => 0.0,
                'download_count' => 0,
                'official_source_name' => 'Developer Preview Portal',
                'official_source_url' => 'https://github.com',
                'status' => 'draft',
                'featured' => false,
                'category_slugs' => ['adventure', 'simulation'],
                'min_req' => ['os' => 'Windows 10 (64-bit)', 'processor' => 'Intel Core i5', 'memory' => '8 GB RAM', 'graphics' => 'GTX 1060 6GB', 'storage' => '3 GB', 'directx' => 'Version 11'],
                'rec_req' => ['os' => 'Windows 11 (64-bit)', 'processor' => 'Intel Core i7', 'memory' => '16 GB RAM', 'graphics' => 'RTX 3060', 'storage' => '5 GB', 'directx' => 'Version 12'],
                'screenshots' => [
                    'https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?auto=format&fit=crop&w=1200&q=80',
                ],
            ],
            [
                'title' => 'Cyber Knight Chronicles (Draft)',
                'slug' => 'cyber-knight-chronicles-draft',
                'short_description' => 'WIP cyberpunk hack and slash action platformer prototype.',
                'description' => 'Cyber Knight Chronicles is an in-development retro-futuristic combat platformer prototype with synthwave soundtrack and lightning fast combat.',
                'developer' => 'Neon Pixel Studios',
                'publisher' => 'Self-published',
                'game_type' => 'freeware',
                'release_date' => '2026-12-01',
                'version' => 'v0.0.5',
                'file_size' => '320 MB',
                'cover_image' => 'https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=600&q=80',
                'banner_image' => 'https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&w=1600&q=80',
                'supported_languages' => ['English'],
                'last_updated' => '2026-03-01',
                'rating' => 0.0,
                'download_count' => 0,
                'official_source_name' => 'Internal Staging',
                'official_source_url' => 'https://github.com',
                'status' => 'draft',
                'featured' => false,
                'category_slugs' => ['action', 'indie'],
                'min_req' => ['os' => 'Windows 10', 'processor' => 'Dual Core 2.0 GHz', 'memory' => '4 GB RAM', 'graphics' => 'DirectX 11 Graphics', 'storage' => '1 GB', 'directx' => 'Version 11'],
                'rec_req' => ['os' => 'Windows 11', 'processor' => 'Quad Core 3.0 GHz', 'memory' => '8 GB RAM', 'graphics' => 'GTX 1050', 'storage' => '2 GB', 'directx' => 'Version 11'],
                'screenshots' => [
                    'https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=1200&q=80',
                ],
            ],
        ];

        foreach ($games as $data) {
            $categorySlugs = $data['category_slugs'];
            $minReq = $data['min_req'];
            $recReq = $data['rec_req'];
            $screenshots = $data['screenshots'];

            unset($data['category_slugs'], $data['min_req'], $data['rec_req'], $data['screenshots']);

            $game = Game::updateOrCreate(['slug' => $data['slug']], $data);

            // Sync Categories
            $catIds = array_values(array_intersect_key($categoriesMap, array_flip($categorySlugs)));
            $game->categories()->sync($catIds);

            // Minimum System Requirements
            GameSystemRequirement::updateOrCreate(
                ['game_id' => $game->id, 'type' => 'minimum'],
                $minReq
            );

            // Recommended System Requirements
            GameSystemRequirement::updateOrCreate(
                ['game_id' => $game->id, 'type' => 'recommended'],
                $recReq
            );

            // Screenshots
            GameScreenshot::where('game_id', $game->id)->delete();
            foreach ($screenshots as $index => $url) {
                GameScreenshot::create([
                    'game_id' => $game->id,
                    'image_url' => $url,
                    'sort_order' => $index + 1,
                ]);
            }
        }
    }
}
